on:
  push:
    branches:
      - main
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: node --version
      - run: npm install --engine-strict
      - run: npm test
